skyline69/balatro-mod-index

mods/nh6574@JoyousSpring/meta.json

I copied the wrong mod name :P

Fix nh6574@JoyousSpring name

---

mods/PinkMaggit@Buffoonery/meta.json

Change Buffoonery to no longer require Talisman

update talisman dependency

---

mods/BakersDozenBagels@Bakery/description.md
mods/BakersDozenBagels@Bakery/meta.json

My misc. content mod. There's not really a cohesive visual identity to use in a thumbnail, so I did not provide one.

Add BakersDozenBagels@Bakery mod

---

mods/Bazinga9000@MathBlinds/description.md
mods/Bazinga9000@MathBlinds/meta.json
mods/JeffVi@DX-Tarots/description.md
mods/JeffVi@DX-Tarots/meta.json
mods/Kooluve@BetterMouseAndGamepad/description.md
mods/Kooluve@BetterMouseAndGamepad/meta.json
mods/SleepyG11@HandyBalatro/description.md
mods/SleepyG11@HandyBalatro/meta.json
mods/kcgidw@kcvanilla/description.md
mods/kcgidw@kcvanilla/meta.json

Indexing older mods that haven't received updates for a while/haven't had their creators active in a while on the discord, alongside KCVanilla and Handy (with owners' permission)

Mod Indexing Wave 1

---

mods/BataBata3@PampaPack/description.md
mods/BataBata3@PampaPack/meta.json
mods/GauntletGames-2086@D6Jokers/description.md
mods/GauntletGames-2086@D6Jokers/meta.json
mods/ItayFeeder@CodexArcanum/description.md
mods/ItayFeeder@CodexArcanum/meta.json
mods/Itayfeder@FusionJokers/description.md
mods/Itayfeder@FusionJokers/meta.json
mods/JamesTheJellyfish@BadApple/description.md
mods/JamesTheJellyfish@BadApple/meta.json
mods/Numbuh214@XCards/description.md
mods/Numbuh214@XCards/meta.json
mods/SleepyG11@HandyBalatro/meta.json
mods/Snoresville@TurbulentJokers/description.md
mods/Snoresville@TurbulentJokers/meta.json
mods/TetraMinus@TetraPak/description.md
mods/TetraMinus@TetraPak/meta.json
mods/iJohnMaged@MultiJokers/description.md
mods/iJohnMaged@MultiJokers/meta.json
mods/lusciousdev@LushMod/description.md
mods/lusciousdev@LushMod/meta.json

Added a bunch of inactive, older mods.
Also fixed an inaccuracy in the Handy Balatro listing

Mod Indexing Batch 2

---

mods/ItayFeeder@CodexArcanum/description.md
mods/ItayFeeder@CodexArcanum/meta.json
mods/jumbocarrot0@ReduxArcanum/description.md
mods/jumbocarrot0@ReduxArcanum/meta.json

Also added Redux Arcanum, so people can decide whether they want original or redux

Replaced Codex Arcanum with a newer fork

---

mods/MathIsFun0@Trance/description.md
mods/MathIsFun0@Trance/meta.json

Not mine obviously but could be a good addition to the index, this mod allows the player to change Balatro's UI colors and font.

Add MathIsFun0@Trance mod

---

mods/Virtualized@Multiplayer/description.md
mods/Virtualized@Multiplayer/meta.json

The Multiplayer mod's stable version now uses latest steamodded, so I am updating the index to the stable version of the mod instead of the experimental one

Updated the Multiplayer mod to use releases instead of the experimental version of the mod

---

mods/ARandomTank7@Balajeweled/description.md

I just realized that i've mispelled Steamodded by adding a second "m", oopsies.
This PR will correct it.

Correct Balajeweled description

---

mods/Breezebuilder@SystemClock/meta.json

Update Breezebuilder@SystemClock version

---

mods/MathIsFun0@Cryptid/description.md
mods/MathIsFun0@Cryptid/meta.json

Main branch is now compatible with Steamodded's main branch

Update Cryptid Metadata

---

mods/stupxd@Cartomancer/meta.json

Update stupxd@Cartomancer version

---

mods/ARandomTank7@Balajeweled/description.md

The recent v0.1.2 update of my mod has added initial face cards support.
This PR will simply update the description to reflect this update.

Update Balajeweled description

---

mods/StarletDevil@AzzysJokers/meta.json

Multiple post-release bugs found and patched

Update StarletDevil@AzzysJokers mod

---

mods/LawyerRed@RWKarmaDeck/description.md
mods/LawyerRed@RWKarmaDeck/meta.json

Adjusted the description to have the correct Steamodded dependency & added a second author to the metadata.

Updated LawyerRed@RWKarmaDeck

---

mods/MathIsFun0@Cryptid/description.md

We changed the vanity link but I forgot to change it here :sob:

Update Cryptid's Discord link

---

mods/Neato@NeatoJokers/description.md
mods/Neato@NeatoJokers/meta.json

Fixes some image issues in description.md, enables `automatic-version-check`.

Neatojokers mod-index update

---

.github/scripts/requirements.txt
.github/workflows/update-mod-versions.yml
mods/MathIsFun0@Cryptid/meta.json

This pull request includes several changes to streamline dependency management, improve workflow efficiency, and update version metadata. The most important changes include adding a new dependency to the requirements file, enabling pip caching, modifying the dependency installation process, and updating the version in the metadata file.
Dependency management improvements:
* [`.github/scripts/requirements.txt`](diffhunk://#diff-39fb8e148594fb30451d9c14478733efb47cf4bea2eed53c0c3b6a6339c8ef1aR1): Added the `requests` library to the requirements file.
Workflow efficiency improvements:
* [`.github/workflows/update-mod-versions.yml`](diffhunk://#diff-08c6175ddce4a9d49c79d12925be3c4f705913aadcd437a10b8bde3bde8fe740R22-R27): Enabled pip caching to speed up dependency installation.
* …

116 implement dependency caching

---

mods/Opal@ChallengerDeep/meta.json

the previous DownloadURL link tries to download the webpage for the latest release - this update should fix that. Apologies

Update Opal@ChallengerDeep mod

---

mods/Blazingulag@Prism/description.md

Update Blazingulag@Prism mod

---

mods/Firch@Bunco/meta.json

Update version and remove autocheck

Update Firch@Bunco mod

---

mods/misenrol@TerrariaXBalatro/description.md

Made a type on the description, is there a better way to fix it instead of creating pull requests?

description.md

---

mods/SkywardTARDIS@ReverseTarotHijinks/description.md
mods/SkywardTARDIS@ReverseTarotHijinks/meta.json

Mod that adds jokers, reverse tarot cards, zodiac consumable cards, new hand type, blinds, and more.

Add SkywardTARDIS@ReverseTarotHijinks mod

---

.github/workflows/check-mod.yml

This pull request updates the `.github/workflows/check-mod.yml` file to improve the process of identifying changed mods in a pull request. The main change involves using the GitHub API to fetch the list of changed files instead of relying on `git fetch` and `git diff` commands.
Improvements to the workflow:
* Replaced the `git fetch` and `git diff` commands with a call to the GitHub API to get the list of files changed in the pull request using a Personal Access Token (PAT). This change improves the reliability and accuracy of identifying changed mods.Use PAT token.

Update mod validation

---

mods/DrFuff@AJollyExpansion/description.md
mods/DrFuff@AJollyExpansion/meta.json

This is a mod that includes 9 jokers and a seal.  they are all meant to reference the Youtuber and twitch streamer A Jolly Wangcore.  the seal doesn't have a consumable as its linked to one of the jokers.

add DrFuff@AJollyExpansion

---

mods/Virtualized@Multiplayer/meta.json

Reverts skyline69/balatro-mod-index#185

Revert "fix `BalatroMultiplayer` failing to load its modules"

---

mods/Mathguy@CruelBlinds/description.md
mods/Mathguy@CruelBlinds/meta.json
mods/Mathguy@Grim/description.md
mods/Mathguy@Grim/meta.json

Grim adds a new skill tree with plentiful content
Cruel Blinds adds multiple blinds which can range from usually difficult to run-ending

Grim & Cruel Blinds

---

README.md

- Added basic rules to clarify that submissions must be safe, legal, and generally inoffensive
- Clarified redistribution terms for submitted mods
- Clarified willingness to remove owned content by request
- Added requirements and guidelines for submitting mods on behalf of others

Add Submission Policy

---

.github/scripts/requirements.lock
.github/scripts/update_mod_versions.py
.github/workflows/update-mod-versions.yml
.gitignore
mods/janw4ld@typist/meta.json

based on #192, will _fix_ itself if its merge-base commit gets merged

janw4ld@typist: switch `downloadURL` to release tag

---

.github/workflows/update-mod-versions.yml

https://peps.python.org/pep-0701/ :)

fix(ci): switch to python3.12 for sensible f-strings

---

mods/Somethingcom515@SealsOnEverything/description.md
mods/Somethingcom515@SealsOnEverything/meta.json

A mod to put seals on basically everything.

Add Somethingcom515@SealsOnEverything mod

---

mods/TheMotherfuckingBearodactyl@Insolence/meta.json

same as #202 because i can't see

mods: enable automatic tag updates for `TheMotherfuckingBearodactyl@Insolence`

---

mods/kasimeka@typist/description.md

the current description is something like
> Typist typist typist is a fully keyb...
which is _sad_

mods(kasimeka@typist): fix description preview

---

mods/riosodu@black-seal/description.md
mods/riosodu@black-seal/meta.json

New mod submission: 'Black Seal' (directory: black-seal)
**Mod Details:**
- Author: riosodu
- Name: Black Seal (Directory: black-seal)
**Mod:** `riosodu@black-seal`
**Description:** Adds a Black Seal to the game with a configurable spawn chance.
**Source Files (in gfreitash/balatro-mods):** https://github.com/gfreitash/balatro-mods/tree/main/black-seal
**Triggering Commit (in gfreitash/balatro-mods):** [19f6727](https://github.com/gfreitash/balatro-mods/commit/19f67274e7170b11365356fe3003a90915f507e4)
---

Add riosodu@black-seal mod

---

mods/wingedcatgirl@MintysSillyMod/meta.json

Minty's Mod version update

---

mods/riosodu@qol-bundle/description.md
mods/riosodu@qol-bundle/meta.json

New mod submission: 'QoL Bundle' (directory: qol-bundle)
**Mod Details:**
- Author: riosodu
- Name: QoL Bundle (Directory: qol-bundle)
**Mod:** `riosodu@qol-bundle`
**Description:** A collection of quality-of-life improvements for Balatro.
**Source Files (in gfreitash/balatro-mods):** https://github.com/gfreitash/balatro-mods/tree/main/qol-bundle
**Triggering Commit (in gfreitash/balatro-mods):** [b90a3f5](https://github.com/gfreitash/balatro-mods/commit/b90a3f525684899bbb51536fdd3d0df08fbece35)
---

Add riosodu@qol-bundle mod

---

mods/ARandomTank7@Balajeweled/description.md

Removed mod name, added Malverk requirement message as of v0.1.3a

Update ARandomTank7@Balajeweled description

---

mods/WUOTE@MagicSort/description.md

Edit WUOTE@MagicSort description

---

mods/OneSuchKeeper@Hunatro/description.md

add note for Malverk support added in latest update

update OneSuchKeeper@Hunatro mod

---

mods/colonthreeing@SealSeal/description.md
mods/colonthreeing@SealSeal/meta.json

Adds the mod SealSeal by me. Source can be found [here](https://github.com/colonthreeing/SealSealBalatro/tree/1.1.0)
It's a mod for making the seals on cards look like seals (the animal).

Add colonthreeing@SealSeal mod

---

mods/LazyTurtle33@TurtlesChallenges/description.md
mods/LazyTurtle33@TurtlesChallenges/meta.json

Adds some Challenges made by LazyTurtle33
Challenges include:
AAAA - deck has only 4 aces. you cant change the deck
AAAA (but fuck you) - same as AAAA but harder
Empty Orbit - no leveling up hands
NOPE - 1 in 4 chance for any action to NOT HAPPEN
All challenges has been beaten by ether me or a play tester

Add LazyTurtle33@TurtlesChallenges mod

---

mods/riosodu@qol-bundle/description.md
mods/riosodu@qol-bundle/meta.json

Automated update of the mod 'QoL Bundle' (directory: qol-bundle) to version `v20250730_050954`.
**Mod:** `riosodu@qol-bundle`
**Description:** A collection of quality-of-life improvements for Balatro.
Changes:
- changed description
**Source Files (in gfreitash/balatro-mods):** https://github.com/gfreitash/balatro-mods/tree/main/qol-bundle
**Triggering Commit (in gfreitash/balatro-mods):** [71bd468](https://github.com/gfreitash/balatro-mods/commit/71bd468a576229439ce1342ebc25e57d9359fe0e)
---

Update riosodu@qol-bundle mod to v20250730_050954

---

mods/Lily@VallKarri/description.md
mods/Lily@VallKarri/meta.json

no longer incompatible with crp, update content quantity info, remove talisman requirement (talisman is optional now)

update vallkarri info

---

mods/LazyTurtle33@TurtlesChallenges/description.md

added a new challenge to the description :3

LazyTurtle33@TurtlesChallenges: update description

---

mods/Stellr@FearsAndPhobias/description.md

Updating description for future-proofing

Update `Stellr@FearsAndPhobias` description

---

mods/wingedcatgirl@MintysSillyMod/meta.json

Update Minty's Silly Little Mod

---

mods/SadCube@ArtBox/description.md
mods/SadCube@ArtBox/meta.json

An art themed mod adding all kinds of stuff! Especially new ways of modifying playing cards. 
Added on behalf of SadCube, as I have also worked on this mod.

Add SadCube@ArtBox

---

mods/Jogla@DebugPlusPlus/description.md
mods/Jogla@DebugPlusPlus/meta.json

A mod that adds an in-game menu to ease some debugging actions.

Add Jogla@DebugPlusPlus mod
