mods/EnderGoodra@Textile/description.md, mods/EnderGoodra@Textile/meta.json
A Balatro mod that modifies the base game's `evaluate()` function, adding in some extra style options for text.
=> Add EnderGoodra@Textile mod

mods/stupxd@Cartomancer/description.md, mods/stupxd@Cartomancer/meta.json
Cartomancer is a mod that gives QoL optimizations to the deck and UI, such as limiting the amount of cards rendered on the deck pile.
=> Add stupxd@Cartomancer mod

mods/TOGAPack@TheOneGoofAli/meta.json
No longer requiring Talisman explicitly.
=> Update TOGAPack meta.json

mods/DivvyCr@Balatro-Preview/description.md, mods/DivvyCr@Balatro-Preview/meta.json
This mod adds a score and money preview of the selected hand.
However, this mod only simulates vanilla jokers for the preview, for modded jokers, it's up to the mod developer to support this mod.
=> Add DivvyCr@Balatro-Preview mod

mods/ItsFlowwey@FlowerPot/meta.json
FlowerPot needs to have its install folder specifically named "Flower-Pot", otherwise it will make the game crash.
Discovered this problem after trying to launch Balatro with FlowerPot installed.
=> Set folderName property for ItsFlowwey@FlowerPot

mods/Itayfeder@FusionJokers/meta.json
Original Fusion Jokers is abandoned and has many critical bugs; this fork fixes those
=> Update Fusion Jokers URL to elbe's fork

.github/scripts/update_mod_versions.py
Currently, the mod index will prioritise using the name of the tag from the latest release version, regardless of the download source provided by the mod. This is problematic for mods using a link to HEAD (`archive/refs/heads/<main>.zip`) as their `downloadURL` but that also have previously created a Release. This PR instead checks if the mod links to HEAD, and uses the corresponding version.
Also included are improvements to error logging and wait time checks when the GitHub REST API rate limits are hit, which appears to be happening with inconsistent frequency. Hopefully these improvements will help to narrow down the cause of the rate limit problems.
- Check if download url links to latest head, and if so, use version of latest commit hash instead of release version
- Merge …
=> Improvements to Version Update Bot

.github/workflows/update-mod-versions.yml
This PR adds a single-line fix to only run the `update-versions` job when the repo matches 'skyline69/balatro-mod-index'. This will prevent the workflow from running automatically in all forks.
=> Disable `update-mod-versions` job on forks

.github/workflows/update-mod-versions.yml, mods/Betmma@BetmmaMods/meta.json
This pull request includes changes to a GitHub Actions workflow and a metadata file for a mod. The most important changes are:
Workflow condition update:
* [`.github/workflows/update-mod-versions.yml`](diffhunk://#diff-08c6175ddce4a9d49c79d12925be3c4f705913aadcd437a10b8bde3bde8fe740L11-R11): Added a condition to the `update-versions` job to run only if the repository is `skyline69/balatro-mod-index`.
Metadata update:
* [`mods/Betmma@BetmmaMods/meta.json`](diffhunk://#diff-91e263ad0127035020f677f4feeeb3759ac5ce30b3a31f27bb0f737629732797L12-R12): Updated the `version` field from `472b774` to `f082372`.
=> Fork issue fix

README.md, mods/r0maps@GigaJokers/meta.json, schema/meta.schema.json
- Set `requires-talisman` as a required parameter in schema
- Marked `requires-talisman` as a required parameter in README
Balatro Mod Manager appears to reject mods without this parameter. While it would ideally not need be required and default to false, for the sake of compatibility with all versions of BMM this is the easiest solution.
=> Set and clarify `requires-talisman` as a required parameter

mods/spire-winder@Balatro-Draft/meta.json
Was incorrectly using a link to the files for Eremel@Galdur.
Manually set version to allow bad previous versions to update, which would otherwise be unaware of the change and remain on `d4fbaeb`
=> Fix spire-winder@Balatro-Draft `downloadURL`

mods/Opal@ChallengerDeep/description.md, mods/Opal@ChallengerDeep/meta.json
Challenger Deep is a mod that adds 100+ Custom Rules for Challenges, including but not limited to:
- Banning specific Editions from appearing
- Permitting Stickers to appear, independent of each other
- Shop modifications, such as forcing Jokers or removing Vouchers/Rerolls
=> Add Opal@ChallengerDeep mod

.github/workflows/check-mod.yml
- Fix invalid use of PAT auth token, replace with standard `secrets.GITHUB_TOKEN`
- Create and use cached ImageMagick installation (fixed version 8:6.9.12.98+dfsg1-5.2build2) for significantly improved runtime
- Previously ~50-90s, now down to ~6-10s
- Run validator steps even when previous validators have failed, to allow reporting multiple errors with a single action:
- Check Thumbnail Dimensions
- Validate JSON Format
- Validate meta.json Against Schema
- Validate Download URLs
=> Improvements to Mod validator `check_mod.yml`

mods/Opal@ChallengerExamples/description.md, mods/Opal@ChallengerExamples/meta.json
Challenger Examples is a mod that adds Challenges focused on Challenger Deep's rules. Currently, there are 7 Challenges.
=> Add Opal@ChallengerExamples

mods/Eremel@Galdur/meta.json, mods/Itayfeder@FusionJokers/meta.json, mods/Larswijn@CardSleeves/meta.json, mods/wingedcatgirl@SpectrumFramework/meta.json
Includes Cardsleeves, FusionJokers, Galdur and SpectrumFramework. Based on https://balatromods.miraheze.org/wiki/Category:API_Mods.
Closes #169
=> Add the API category to 4 mods

.github/workflows/check-mod.yml
- Simplify creation of META_JSON_FILES list
- Provide multi-line `META_JSON_FILES` to `$GITHUB_OUTPUT` using [recommended syntax](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#multiline-strings)
=> Fix `meta.json` validator failing when multiple mods changed

mods/StarletDevil@AzzysJokers/meta.json
this mod used a release tag (with no extra assets) and originally had `automatic-verison-check: true`, although auto updates for tags weren't implemented, so this field was set to `false` by index maintainers. now that this is supported im making this patch to restore `automatic-version-check`
=> revert <https://github.com/skyline69/balatro-mod-index/commit/6731690> where unnecessary

mods/Fantom@Fantom'sPreview/description.md, mods/Fantom@Fantom'sPreview/meta.json
Fantom's Preview is a version of Divvy's Preview specifically made for use with the Multiplayer Mod. Gives a button which can be pressed for a score preview.
=> Add Fantom's Preview

mods/Eramdam@StickyFingers/meta.json
I've fixed the structure of the mod such that all the lovely files are at the root, meaning I _should_ be able to remove `folderName` which was causing issues (I assumed it meant BMM would look for `$MODS/sticky-fingers/sticky-fingers` and not `$MODS/sticky-fingers` 😅
=> [Sticky Fingers] Remove `folderName` field

mods/Firch@Bunco/meta.json
The current link crashes on startup with latest Steamodded; this version fixes that error.
=> Update Bunco link to jumbocarrot's fork

mods/its-edalo@slay-the-jokers/description.md
The main change is the upload key path written in the setup instructions - the old setup used an upload key file path that was overwritten by the Mod Manager each update. The path was moved to the `Balatro` data folder to solve that, so the description needs to be updated too.
The smaller change is adding a note about not closing the black window (some users that were new to the Mod Manager closed it, stopping the uploads)
=> Changed Slay the Jokers' setup instructions to be compatible with the Mod Manager

mods/riosodu@rebalanced-stakes/description.md, mods/riosodu@rebalanced-stakes/meta.json
New mod submission: 'Rebalanced Stakes' (directory: rebalanced-stakes)
**Mod Details:**
- Author: riosodu
- Name: Rebalanced Stakes (Directory: rebalanced-stakes)
**Mod:** `riosodu@rebalanced-stakes`
**Description:** Removes the -1 discard from blue stake, moving joker stickers to earlier stakes while completely reworking the gold stake to still be a challenge without restricting played hands
**Source Files (in gfreitash/balatro-mods):** https://github.com/gfreitash/balatro-mods/tree/main/rebalanced-stakes
**Triggering Commit (in gfreitash/balatro-mods):** [30b38ae](https://github.com/gfreitash/balatro-mods/commit/30b38ae6611296ea255549e050b1fb34730b243f)
---
=> Add riosodu@rebalanced-stakes mod

mods/Glitchkat10@Cryptposting/description.md, mods/Glitchkat10@Cryptposting/meta.json
Add Cryptposting, a relatively new mod that is garnering popularity, to the Balatro Mod Index.
=> Add Cryptposting to the Balatro Mod Index

mods/Mathguy@CruelBlinds/meta.json, mods/Mathguy@Grim/meta.json, schema/meta.schema.json
i don't think the version field should be optional, since part of a mod manager's functionality is keeping track of versions to detect updates, if a user's mod won't ever be versioned or receive updates they can just set the version field to _anything_ and disable auto version checks instead of omitting the field.
=> fix?(schema): make `version` a required field.

.github/workflows/check-mod.yml
ive been always puzzled by what kind of environment is the schema check deploying or why is the deployments api being invoked instead of `check-mods` being a pure check but never actually bothered to read the action
=> chore: delete meaningless check-mod step

mods/GoonsTowerDefense@Goonlatro/description.md, mods/GoonsTowerDefense@Goonlatro/meta.json
A mod and texture pack for Balatro that adds various Jokers and Consumables to the game based on GTD Discord references.
=> Add GoonsTowerDefense@Goonlatro

mods/riosodu@black-seal/meta.json
Automated update of the mod 'Black Seal' (directory: black-seal) to version `v20250902_120043`.
**Mod:** `riosodu@black-seal`
**Description:** Adds a Black Seal to the game with a configurable spawn chance.
Changes:
- changed metadata
**Source Files (in gfreitash/balatro-mods):** https://github.com/gfreitash/balatro-mods/tree/main/black-seal
**Triggering Commit (in gfreitash/balatro-mods):** [a1e5fcb](https://github.com/gfreitash/balatro-mods/commit/a1e5fcb61ec070117540d4556eaa6a90a75f08e7)
---
=> Update riosodu@black-seal mod to v20250902_120043

mods/Maelmc@Pokermon-Maelmc/description.md, mods/Maelmc@Pokermon-Maelmc/meta.json
A Pokermon extension, that adds Pokémon-related jokers, consumables and other things that aren't (yet) featured in InertSteak's Pokermon mod.
=> Add Maelmc@Pokermon-Maelmc mod
